name: Deploy (Auxbot-Staging)

on:
  push:
    branches:
      - Staging

jobs:
  build:
    environment: auxbot-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKUAPI}}
          heroku_app_name: ${{secrets.HEROKUAPP}}
          heroku_email: ${{secrets.HEROKUEMAIL}}
        env:
          HD_TOKEN: ${{secrets.TOKEN}}
          HD_STAGEPINGURL: ${{secrets.STAGEPINGURL}}
          HD_MASTERPINGURL: ${{secrets.MASTERPINGURL}}
